import { RadioStation } from './radioService.js';

/**
 * Список радиостанций со всего мира
 * Все URL используют HTTPS и являются прямыми потоками
 */
export const fallbackStations: RadioStation[] = [
    // === ФРАНЦИЯ ===
    {
        name: 'FIP Radio',
        url: 'https://icecast.radiofrance.fr/fip-midfi.mp3',
        homepage: 'https://www.radiofrance.fr/fip',
        favicon: 'https://www.radiofrance.fr/favicon.ico',
        tags: ['eclectic', 'jazz', 'world'],
        country: 'France',
        language: 'french',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'France Culture',
        url: 'https://icecast.radiofrance.fr/franceculture-midfi.mp3',
        homepage: 'https://www.radiofrance.fr/franceculture',
        favicon: 'https://www.radiofrance.fr/favicon.ico',
        tags: ['culture', 'talk', 'news'],
        country: 'France',
        language: 'french',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'France Musique',
        url: 'https://icecast.radiofrance.fr/francemusique-midfi.mp3',
        homepage: 'https://www.radiofrance.fr/francemusique',
        favicon: 'https://www.radiofrance.fr/favicon.ico',
        tags: ['classical', 'jazz'],
        country: 'France',
        language: 'french',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'France Inter',
        url: 'https://icecast.radiofrance.fr/franceinter-midfi.mp3',
        homepage: 'https://www.radiofrance.fr/franceinter',
        favicon: 'https://www.radiofrance.fr/favicon.ico',
        tags: ['talk', 'news', 'culture'],
        country: 'France',
        language: 'french',
        codec: 'MP3',
        bitrate: 128,
    },

    // === США ===
    {
        name: 'KEXP Seattle',
        url: 'https://kexp-mp3-128.streamguys1.com/kexp128.mp3',
        homepage: 'https://www.kexp.org',
        favicon: 'https://www.kexp.org/favicon.ico',
        tags: ['indie', 'alternative', 'rock'],
        country: 'USA',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'SomaFM Groove Salad',
        url: 'https://ice2.somafm.com/groovesalad-128-mp3',
        homepage: 'https://somafm.com/groovesalad/',
        favicon: 'https://somafm.com/favicon.ico',
        tags: ['electronic', 'ambient', 'chillout'],
        country: 'USA',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'SomaFM Indie Pop Rocks',
        url: 'https://ice2.somafm.com/indiepop-128-mp3',
        homepage: 'https://somafm.com/indiepop/',
        favicon: 'https://somafm.com/favicon.ico',
        tags: ['indie', 'pop', 'rock'],
        country: 'USA',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'SomaFM Secret Agent',
        url: 'https://ice2.somafm.com/secretagent-128-mp3',
        homepage: 'https://somafm.com/secretagent/',
        favicon: 'https://somafm.com/favicon.ico',
        tags: ['lounge', 'jazz', 'electronic'],
        country: 'USA',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'SomaFM DEF CON Radio',
        url: 'https://ice2.somafm.com/defcon-128-mp3',
        homepage: 'https://somafm.com/defcon/',
        favicon: 'https://somafm.com/favicon.ico',
        tags: ['electronic', 'techno', 'industrial'],
        country: 'USA',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'SomaFM Drone Zone',
        url: 'https://ice2.somafm.com/dronezone-128-mp3',
        homepage: 'https://somafm.com/dronezone/',
        favicon: 'https://somafm.com/favicon.ico',
        tags: ['ambient', 'drone', 'electronic'],
        country: 'USA',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Jazz24',
        url: 'https://live.wostreaming.net/direct/ppm-jazz24mp3-ibc1',
        homepage: 'https://www.jazz24.org',
        favicon: 'https://www.jazz24.org/favicon.ico',
        tags: ['jazz'],
        country: 'USA',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ВЕЛИКОБРИТАНИЯ ===
    {
        name: 'BBC Radio 1',
        url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_one',
        homepage: 'https://www.bbc.co.uk/radio1',
        favicon: 'https://www.bbc.co.uk/favicon.ico',
        tags: ['pop', 'dance', 'hip hop'],
        country: 'UK',
        language: 'english',
        codec: 'AAC',
        bitrate: 128,
    },
    {
        name: 'BBC Radio 2',
        url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_two',
        homepage: 'https://www.bbc.co.uk/radio2',
        favicon: 'https://www.bbc.co.uk/favicon.ico',
        tags: ['pop', 'rock', 'adult contemporary'],
        country: 'UK',
        language: 'english',
        codec: 'AAC',
        bitrate: 128,
    },
    {
        name: 'BBC Radio 3',
        url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_three',
        homepage: 'https://www.bbc.co.uk/radio3',
        favicon: 'https://www.bbc.co.uk/favicon.ico',
        tags: ['classical', 'jazz', 'world'],
        country: 'UK',
        language: 'english',
        codec: 'AAC',
        bitrate: 128,
    },
    {
        name: 'BBC Radio 4',
        url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_radio_fourfm',
        homepage: 'https://www.bbc.co.uk/radio4',
        favicon: 'https://www.bbc.co.uk/favicon.ico',
        tags: ['talk', 'news', 'culture'],
        country: 'UK',
        language: 'english',
        codec: 'AAC',
        bitrate: 128,
    },
    {
        name: 'BBC Radio 6 Music',
        url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_6music',
        homepage: 'https://www.bbc.co.uk/6music',
        favicon: 'https://www.bbc.co.uk/favicon.ico',
        tags: ['alternative', 'indie', 'rock'],
        country: 'UK',
        language: 'english',
        codec: 'AAC',
        bitrate: 128,
    },
    {
        name: 'BBC World Service',
        url: 'https://stream.live.vc.bbcmedia.co.uk/bbc_world_service',
        homepage: 'https://www.bbc.co.uk/worldservice',
        favicon: 'https://www.bbc.co.uk/favicon.ico',
        tags: ['news', 'talk'],
        country: 'UK',
        language: 'english',
        codec: 'AAC',
        bitrate: 128,
    },

    // === ГЕРМАНИЯ ===
    {
        name: 'Deutschlandfunk',
        url: 'https://st01.sslstream.dlf.de/dlf/01/128/mp3/stream.mp3',
        homepage: 'https://www.deutschlandfunk.de',
        favicon: 'https://www.deutschlandfunk.de/favicon.ico',
        tags: ['news', 'talk', 'culture'],
        country: 'Germany',
        language: 'german',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Deutschlandfunk Kultur',
        url: 'https://st02.sslstream.dlf.de/dlf/02/128/mp3/stream.mp3',
        homepage: 'https://www.deutschlandfunkkultur.de',
        favicon: 'https://www.deutschlandfunkkultur.de/favicon.ico',
        tags: ['culture', 'classical', 'talk'],
        country: 'Germany',
        language: 'german',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Deutschlandfunk Nova',
        url: 'https://st03.sslstream.dlf.de/dlf/03/128/mp3/stream.mp3',
        homepage: 'https://www.deutschlandfunknova.de',
        favicon: 'https://www.deutschlandfunknova.de/favicon.ico',
        tags: ['pop', 'electronic', 'talk'],
        country: 'Germany',
        language: 'german',
        codec: 'MP3',
        bitrate: 128,
    },

    // === НИДЕРЛАНДЫ ===
    {
        name: 'NPO Radio 1',
        url: 'https://icecast.omroep.nl/radio1-bb-mp3',
        homepage: 'https://www.nporadio1.nl',
        favicon: 'https://www.npo.nl/favicon.ico',
        tags: ['news', 'talk'],
        country: 'Netherlands',
        language: 'dutch',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'NPO Radio 2',
        url: 'https://icecast.omroep.nl/radio2-bb-mp3',
        homepage: 'https://www.nporadio2.nl',
        favicon: 'https://www.npo.nl/favicon.ico',
        tags: ['pop', 'rock'],
        country: 'Netherlands',
        language: 'dutch',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'NPO 3FM',
        url: 'https://icecast.omroep.nl/3fm-bb-mp3',
        homepage: 'https://www.npo3fm.nl',
        favicon: 'https://www.npo.nl/favicon.ico',
        tags: ['pop', 'alternative', 'indie'],
        country: 'Netherlands',
        language: 'dutch',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'NPO Radio 4',
        url: 'https://icecast.omroep.nl/radio4-bb-mp3',
        homepage: 'https://www.nporadio4.nl',
        favicon: 'https://www.npo.nl/favicon.ico',
        tags: ['classical'],
        country: 'Netherlands',
        language: 'dutch',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ШВЕЙЦАРИЯ ===
    {
        name: 'SRF 1',
        url: 'https://stream.srg-ssr.ch/m/drs1/mp3_128',
        homepage: 'https://www.srf.ch/radio-srf-1',
        favicon: 'https://www.srf.ch/favicon.ico',
        tags: ['pop', 'talk', 'news'],
        country: 'Switzerland',
        language: 'german',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'SRF 2 Kultur',
        url: 'https://stream.srg-ssr.ch/m/drs2/mp3_128',
        homepage: 'https://www.srf.ch/radio-srf-2-kultur',
        favicon: 'https://www.srf.ch/favicon.ico',
        tags: ['culture', 'classical', 'jazz'],
        country: 'Switzerland',
        language: 'german',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'SRF 3',
        url: 'https://stream.srg-ssr.ch/m/drs3/mp3_128',
        homepage: 'https://www.srf.ch/radio-srf-3',
        favicon: 'https://www.srf.ch/favicon.ico',
        tags: ['pop', 'rock', 'electronic'],
        country: 'Switzerland',
        language: 'german',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ИТАЛИЯ ===
    {
        name: 'RAI Radio 1',
        url: 'https://icestreaming.rai.it/1.mp3',
        homepage: 'https://www.raiplayradio.it/radio1',
        favicon: 'https://www.rai.it/favicon.ico',
        tags: ['news', 'talk'],
        country: 'Italy',
        language: 'italian',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'RAI Radio 2',
        url: 'https://icestreaming.rai.it/2.mp3',
        homepage: 'https://www.raiplayradio.it/radio2',
        favicon: 'https://www.rai.it/favicon.ico',
        tags: ['pop', 'entertainment'],
        country: 'Italy',
        language: 'italian',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'RAI Radio 3',
        url: 'https://icestreaming.rai.it/3.mp3',
        homepage: 'https://www.raiplayradio.it/radio3',
        favicon: 'https://www.rai.it/favicon.ico',
        tags: ['classical', 'culture', 'jazz'],
        country: 'Italy',
        language: 'italian',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ИСПАНИЯ ===
    {
        name: 'RNE Radio Nacional',
        url: 'https://rtvelivestream.akamaized.net/rne_r1_main.mp3',
        homepage: 'https://www.rtve.es/radio/radio-nacional',
        favicon: 'https://www.rtve.es/favicon.ico',
        tags: ['news', 'talk', 'culture'],
        country: 'Spain',
        language: 'spanish',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Radio Clásica',
        url: 'https://rtvelivestream.akamaized.net/rne_r2_main.mp3',
        homepage: 'https://www.rtve.es/radio/radio-clasica',
        favicon: 'https://www.rtve.es/favicon.ico',
        tags: ['classical'],
        country: 'Spain',
        language: 'spanish',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Radio 3',
        url: 'https://rtvelivestream.akamaized.net/rne_r3_main.mp3',
        homepage: 'https://www.rtve.es/radio/radio3',
        favicon: 'https://www.rtve.es/favicon.ico',
        tags: ['alternative', 'indie', 'rock'],
        country: 'Spain',
        language: 'spanish',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ЯПОНИЯ ===
    {
        name: 'J-Wave Tokyo',
        url: 'https://stream.j-wave.co.jp/jwave/jwave.aac',
        homepage: 'https://www.j-wave.co.jp',
        favicon: 'https://www.j-wave.co.jp/favicon.ico',
        tags: ['pop', 'electronic', 'talk'],
        country: 'Japan',
        language: 'japanese',
        codec: 'AAC',
        bitrate: 128,
    },

    // === АВСТРАЛИЯ ===
    {
        name: 'Triple J',
        url: 'https://live-radio01.mediahubaustralia.com/2TJW/mp3/',
        homepage: 'https://www.abc.net.au/triplej',
        favicon: 'https://www.abc.net.au/favicon.ico',
        tags: ['alternative', 'indie', 'rock'],
        country: 'Australia',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'ABC Classic',
        url: 'https://live-radio01.mediahubaustralia.com/2FMW/mp3/',
        homepage: 'https://www.abc.net.au/classic',
        favicon: 'https://www.abc.net.au/favicon.ico',
        tags: ['classical'],
        country: 'Australia',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'ABC Jazz',
        url: 'https://live-radio01.mediahubaustralia.com/JAZW/mp3/',
        homepage: 'https://www.abc.net.au/jazz',
        favicon: 'https://www.abc.net.au/favicon.ico',
        tags: ['jazz'],
        country: 'Australia',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },

    // === НОВАЯ ЗЕЛАНДИЯ ===
    {
        name: 'Radio New Zealand National',
        url: 'https://livestream.radionz.co.nz/national/national.stream/playlist.m3u8',
        homepage: 'https://www.rnz.co.nz/national',
        favicon: 'https://www.rnz.co.nz/favicon.ico',
        tags: ['news', 'talk', 'culture'],
        country: 'New Zealand',
        language: 'english',
        codec: 'HLS',
        bitrate: 128,
    },

    // === КАНАДА ===
    {
        name: 'CBC Radio One Toronto',
        url: 'https://cbcliveradio-lh.akamaihd.net/i/CBCR1_TOR@118420/master.m3u8',
        homepage: 'https://www.cbc.ca/radio',
        favicon: 'https://www.cbc.ca/favicon.ico',
        tags: ['news', 'talk'],
        country: 'Canada',
        language: 'english',
        codec: 'HLS',
        bitrate: 128,
    },
    {
        name: 'CBC Music',
        url: 'https://cbcliveradio-lh.akamaihd.net/i/CBCR2_TOR@382795/master.m3u8',
        homepage: 'https://www.cbc.ca/music',
        favicon: 'https://www.cbc.ca/favicon.ico',
        tags: ['pop', 'rock', 'indie'],
        country: 'Canada',
        language: 'english',
        codec: 'HLS',
        bitrate: 128,
    },

    // === БРАЗИЛИЯ ===
    {
        name: 'Radio Cultura Brasil',
        url: 'https://stream.radiocultura.fm.br:8090/live',
        homepage: 'https://www.radioculturabrasil.com.br',
        favicon: 'https://www.radioculturabrasil.com.br/favicon.ico',
        tags: ['culture', 'mpb', 'talk'],
        country: 'Brazil',
        language: 'portuguese',
        codec: 'MP3',
        bitrate: 128,
    },

    // === РОССИЯ ===
    {
        name: 'Radio Jazz FM',
        url: 'https://nashe1.hostingradio.ru:80/jazz-128.mp3',
        homepage: 'https://www.jazzfm.ru',
        favicon: 'https://www.jazzfm.ru/favicon.ico',
        tags: ['jazz'],
        country: 'Russia',
        language: 'russian',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ЮЖНАЯ КОРЕЯ ===
    {
        name: 'KBS Classic FM',
        url: 'https://kongbuster.duckdns.org:8443/stream/kbs1fm.ogg',
        homepage: 'https://www.kbs.co.kr',
        favicon: 'https://www.kbs.co.kr/favicon.ico',
        tags: ['classical'],
        country: 'South Korea',
        language: 'korean',
        codec: 'OGG',
        bitrate: 128,
    },

    // === ИРЛАНДИЯ ===
    {
        name: 'RTE Radio 1',
        url: 'https://icecast2.rte.ie/radio1.mp3',
        homepage: 'https://www.rte.ie/radio1',
        favicon: 'https://www.rte.ie/favicon.ico',
        tags: ['news', 'talk', 'culture'],
        country: 'Ireland',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'RTE 2FM',
        url: 'https://icecast2.rte.ie/2fm.mp3',
        homepage: 'https://www.rte.ie/2fm',
        favicon: 'https://www.rte.ie/favicon.ico',
        tags: ['pop', 'dance', 'electronic'],
        country: 'Ireland',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'RTE Lyric FM',
        url: 'https://icecast2.rte.ie/lyricfm.mp3',
        homepage: 'https://www.rte.ie/lyricfm',
        favicon: 'https://www.rte.ie/favicon.ico',
        tags: ['classical', 'jazz'],
        country: 'Ireland',
        language: 'english',
        codec: 'MP3',
        bitrate: 128,
    },

    // === НОРВЕГИЯ ===
    {
        name: 'NRK P1',
        url: 'https://lyd.nrk.no/nrk_radio_p1_ostlandssendingen_mp3_h',
        homepage: 'https://www.nrk.no/radio/p1',
        favicon: 'https://www.nrk.no/favicon.ico',
        tags: ['pop', 'talk', 'news'],
        country: 'Norway',
        language: 'norwegian',
        codec: 'MP3',
        bitrate: 192,
    },
    {
        name: 'NRK P2',
        url: 'https://lyd.nrk.no/nrk_radio_p2_mp3_h',
        homepage: 'https://www.nrk.no/radio/p2',
        favicon: 'https://www.nrk.no/favicon.ico',
        tags: ['culture', 'classical', 'jazz'],
        country: 'Norway',
        language: 'norwegian',
        codec: 'MP3',
        bitrate: 192,
    },
    {
        name: 'NRK P3',
        url: 'https://lyd.nrk.no/nrk_radio_p3_mp3_h',
        homepage: 'https://www.nrk.no/radio/p3',
        favicon: 'https://www.nrk.no/favicon.ico',
        tags: ['pop', 'electronic', 'hip hop'],
        country: 'Norway',
        language: 'norwegian',
        codec: 'MP3',
        bitrate: 192,
    },

    // === ШВЕЦИЯ ===
    {
        name: 'Sveriges Radio P1',
        url: 'https://sverigesradio.se/topsy/direkt/132-hi-mp3.m3u',
        homepage: 'https://sverigesradio.se/p1',
        favicon: 'https://sverigesradio.se/favicon.ico',
        tags: ['news', 'talk', 'culture'],
        country: 'Sweden',
        language: 'swedish',
        codec: 'MP3',
        bitrate: 192,
    },
    {
        name: 'Sveriges Radio P2',
        url: 'https://sverigesradio.se/topsy/direkt/2562-hi-mp3.m3u',
        homepage: 'https://sverigesradio.se/p2',
        favicon: 'https://sverigesradio.se/favicon.ico',
        tags: ['classical', 'jazz'],
        country: 'Sweden',
        language: 'swedish',
        codec: 'MP3',
        bitrate: 192,
    },
    {
        name: 'Sveriges Radio P3',
        url: 'https://sverigesradio.se/topsy/direkt/164-hi-mp3.m3u',
        homepage: 'https://sverigesradio.se/p3',
        favicon: 'https://sverigesradio.se/favicon.ico',
        tags: ['pop', 'rock', 'electronic'],
        country: 'Sweden',
        language: 'swedish',
        codec: 'MP3',
        bitrate: 192,
    },

    // === ПОЛЬША ===
    {
        name: 'Polskie Radio Program 1',
        url: 'https://stream1.polskieradio.pl:8902/;stream.mp3',
        homepage: 'https://www.polskieradio.pl/jedynka',
        favicon: 'https://www.polskieradio.pl/favicon.ico',
        tags: ['news', 'talk'],
        country: 'Poland',
        language: 'polish',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Polskie Radio Program 3',
        url: 'https://stream1.polskieradio.pl:8904/;stream.mp3',
        homepage: 'https://www.polskieradio.pl/trojka',
        favicon: 'https://www.polskieradio.pl/favicon.ico',
        tags: ['rock', 'pop', 'alternative'],
        country: 'Poland',
        language: 'polish',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ЧЕХИЯ ===
    {
        name: 'Czech Radio Vltava',
        url: 'https://rozhlas.stream/vltava_128.mp3',
        homepage: 'https://vltava.rozhlas.cz',
        favicon: 'https://www.rozhlas.cz/favicon.ico',
        tags: ['classical', 'jazz', 'culture'],
        country: 'Czech Republic',
        language: 'czech',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Czech Radio Wave',
        url: 'https://rozhlas.stream/wave_128.mp3',
        homepage: 'https://wave.rozhlas.cz',
        favicon: 'https://www.rozhlas.cz/favicon.ico',
        tags: ['alternative', 'indie', 'electronic'],
        country: 'Czech Republic',
        language: 'czech',
        codec: 'MP3',
        bitrate: 128,
    },

    // === АВСТРИЯ ===
    {
        name: 'Ö1',
        url: 'https://orf-live.ors-shoutcast.at/oe1-q2a',
        homepage: 'https://oe1.orf.at',
        favicon: 'https://orf.at/favicon.ico',
        tags: ['classical', 'culture', 'news'],
        country: 'Austria',
        language: 'german',
        codec: 'AAC',
        bitrate: 128,
    },
    {
        name: 'Ö3',
        url: 'https://orf-live.ors-shoutcast.at/oe3-q2a',
        homepage: 'https://oe3.orf.at',
        favicon: 'https://orf.at/favicon.ico',
        tags: ['pop', 'rock'],
        country: 'Austria',
        language: 'german',
        codec: 'AAC',
        bitrate: 128,
    },
    {
        name: 'FM4',
        url: 'https://orf-live.ors-shoutcast.at/fm4-q2a',
        homepage: 'https://fm4.orf.at',
        favicon: 'https://orf.at/favicon.ico',
        tags: ['alternative', 'electronic', 'indie'],
        country: 'Austria',
        language: 'german',
        codec: 'AAC',
        bitrate: 128,
    },

    // === БЕЛЬГИЯ ===
    {
        name: 'Studio Brussel',
        url: 'https://icecast.vrtcdn.be/stubru-high.mp3',
        homepage: 'https://stubru.be',
        favicon: 'https://stubru.be/favicon.ico',
        tags: ['alternative', 'rock', 'electronic'],
        country: 'Belgium',
        language: 'dutch',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Radio 1 Belgium',
        url: 'https://icecast.vrtcdn.be/radio1-high.mp3',
        homepage: 'https://radio1.be',
        favicon: 'https://radio1.be/favicon.ico',
        tags: ['news', 'talk'],
        country: 'Belgium',
        language: 'dutch',
        codec: 'MP3',
        bitrate: 128,
    },
    {
        name: 'Klara',
        url: 'https://icecast.vrtcdn.be/klara-high.mp3',
        homepage: 'https://klara.be',
        favicon: 'https://klara.be/favicon.ico',
        tags: ['classical', 'jazz'],
        country: 'Belgium',
        language: 'dutch',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ФИНЛЯНДИЯ ===
    {
        name: 'Yle Radio 1',
        url: 'https://yleradiolive.akamaized.net/hls/live/2027671/yleradio1/yleradio1.m3u8',
        homepage: 'https://yle.fi/radio1',
        favicon: 'https://yle.fi/favicon.ico',
        tags: ['news', 'talk', 'culture'],
        country: 'Finland',
        language: 'finnish',
        codec: 'HLS',
        bitrate: 128,
    },

    // === ГРЕЦИЯ ===
    {
        name: 'ERT Trito',
        url: 'https://radiostreaming.ert.gr/ert-trito',
        homepage: 'https://www.ert.gr/trito',
        favicon: 'https://www.ert.gr/favicon.ico',
        tags: ['classical', 'jazz', 'culture'],
        country: 'Greece',
        language: 'greek',
        codec: 'MP3',
        bitrate: 128,
    },

    // === ИНДИЯ ===
    {
        name: 'All India Radio FM Gold',
        url: 'https://air.pc.cdn.bitgravity.com/air/live/pbaudio059/playlist.m3u8',
        homepage: 'https://www.allindiaradio.gov.in',
        favicon: 'https://www.allindiaradio.gov.in/favicon.ico',
        tags: ['indian', 'pop', 'bollywood'],
        country: 'India',
        language: 'hindi',
        codec: 'HLS',
        bitrate: 128,
    },

    // === МОНГОЛИЯ ===
    {
        name: 'MNB Radio',
        url: 'https://stream.mnb.mn/live/mnb_radio/playlist.m3u8',
        homepage: 'https://www.mnb.mn',
        favicon: 'https://www.mnb.mn/favicon.ico',
        tags: ['news', 'talk', 'culture'],
        country: 'Mongolia',
        language: 'mongolian',
        codec: 'HLS',
        bitrate: 128,
    },
];
